
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    name: Build and push
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
          architecture: 'x64'
      
      - name: build executable
        run: |
          pip install .
          pip install -r requirements-dev.txt
          pyinstaller --name igtcloud -F -p src .github/workflows/cli.py

      - name: Release
        uses: softprops/action-gh-release@v1
        
        with:
          draft: ${{ startsWith(github.ref, 'refs/tags/') }}
          files: |
            dist/igtcloud*
            LICENSE
          

